### ISSUE TITLE
preload_tag not working with font_url filter

### ISSUE THREAD

**Issue by adictonator** [Shopify/theme-tools#420] opened 2023-12-19 17:36 UTC
**Describe the bug**
Using `font_url` in the `preload_tag` filter to preload font assets throws an error in theme editor.

**Expected**

The `preload_tag` filter should work with the `font_url` and not just `asset_url`.

**Actual**

Upon converting the `<link>` tag with the `preload_tag` filter, the Liquid error starts to show up in the theme editor.

**Stack trace**
This is the error you see in the theme editor at the top.
```
Liquid error (layout/theme line 24): Input must be a theme or shop asset URL
```

**Debugging information**
- OS: Windows and Mac
- Version: 1.11.0

**Additional context**

![image](https://github.com/Shopify/theme-check/assets/20379141/ee1eaaa9-2766-41ac-93b1-11e859638b10)

**Comment by charlespwd** [comment] 2024-10-17 19:49
Duplicate of [The AssetPreload check suggests using preload_tag on font_url assets, which is not supported](https://github.com/Shopify/theme-tools/issues/411)

**Closed by charlespwd** 2024-10-17 19:49 UTC
Labels: Bug, area:theme-check
